### ISSUE TITLE
msgid duplicates behaviour

### ISSUE THREAD

**Issue by cloud-walker** [andris9/gettext-parser#11]
If I got duplicate msgid's on my po the po.parse does not throw any exceptions...

For example:
```gettext
# it.po
msgid "apple"
msgstr "mela"

msgid "apple"
msgstr "melania"
```

Compiles to:
```gettext
it.compiled.po
msgid ""
msgstr "Content-Type: text/plain;\n"

msgid "apple"
msgstr "melania"
```

Keeping only the last msgid...

**Comment by andris9** [comment]
Seems like a correct behavior to me

**Comment by cloud-walker** [comment]
Can you explain why? Thanks in advance.
