### ISSUE TITLE
Silent error doesnt compile my .po

### ISSUE THREAD

**Issue by cloud-walker** [andris9/gettext-parser#14]
In my application I have some broken .po:

```gettext
msgid "%s appunti e documenti condivisi da studenti in tutta Italia"
msgstr "%s notas e documentos compartilhados por estudantes de todo o mundo"

msgid "documenti per %s"
msgstr "documentos por %s""
```

There is a double quote duplication on the last line. Using gettext-parser no error was raised... what should I do? Its a bug? Or should I use a linter? If so there is something out there?

**Comment by andris9** [comment]
gettext-parser is a forgiving parser, it never raises errors. The parser tries to fetch as much data as possible, even if the file is not valid

**Comment by cloud-walker** [comment]
What's the point of a forgiving compiler?

BTW, if so I think it should be noted on the documentation (README?).

As it is now I cant use this repo...
I have to switch to something else as dependency for my [package](https://github.com/cloud-walker/gulp-gettext).

**Comment by andris9** [comment]
It's the parser that is forgiving, not the compiler. If you parse an aivalid file then you end up with some kind of represenation of the parsed data. If you compile this data back to po or mo, then it is compiled exactly as defined in the data structure.
