### ISSUE TITLE
UTF-8 issue using readFileSync()

### ISSUE THREAD

**Issue by leoselig** [andris9/gettext-parser#7]
My umlauts are not parsed correctly from my utf8-encoded .po file using the following script

```javascript
gettextParser.po.parse(
    fs.readFileSync(poFileName)
).translations['']
```

However, this works:

```javascript
gettextParser.po.parse(
    fs.readFileSync(poFileName).toString()
).translations['']
```

**Comment by andris9** [comment]
Probably your po file does not specify the used charset with the content-type header and iso-8859-1 is used by default. If you want to use another default encoding, set it with the second paramater for `parse`

    gettextParser.po.parse(fs.readFileSync(poFileName), 'utf-8').translations['']

**Comment by leoselig** [comment]
Okay, got it
But do you know where the specifications for those headers can be found?
